# Generated by Django 5.2.3 on 2026-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous_refresh_jti',
            field=models.CharField(blank=True, max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='refresh_jti',
            field=models.CharField(blank=True, max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
