# Generated by Django 5.2.3 on 2026-08-16 10:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_ninja', '0002_session_refresh_token_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
