name: Publish to PyPI
on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        working-directory: ${{ github.workspace }}

      # Install necessary utilities (curl, jq, and git)
      - name: Install curl jq git
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq git

      # Get version and release notes from Release Drafter
      - name: Extract version and release notes
        id: release
        run: |
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          NOTES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            ${{ github.event.release.url }} | jq -r '.body')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      # Update pyproject.toml with version
      - name: Update pyproject.toml version
        run: |
          sed -i "s/version = \".*\"/version = \"${{ steps.release.outputs.VERSION }}\"/" pyproject.toml
        working-directory: ${{ github.workspace }}

      # Commit changes
      - name: Commit version and changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pyproject.toml
          git commit -m "chore: update version to ${{ steps.release.outputs.VERSION }} and changelog"
          git push
        working-directory: ${{ github.workspace }}

      - name: Build package
        run: uv build
        working-directory: ${{ github.workspace }}

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
        run: uv publish dist/*-${{ steps.release.outputs.VERSION }}* --token $UV_PUBLISH_TOKEN
        working-directory: ${{ github.workspace }}